add_newline = false

format = """
$username\
$directory\
$git_branch\
$git_status\
$character
"""

right_format = """
$docker_context\
$c\
$deno\
$dotnet\
$golang\
$java\
$kotlin\
$gradle\
$lua\
$nodejs\
$php\
$python\
$ruby\
$rust\
$scala\
$swift\
$zig\
$aws\
$azure\
"""

[character]
format = " $symbol "
success_symbol = "[➜](bold purple)"
error_symbol = "[➜](red)"
vimcmd_symbol = "[➜](dimmed green)"

[username]
style_user = "white"
format = "[ $user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '@[$hostname](bold purple) '
disabled = false

[directory]
format = "[ $path](bold $style)[$read_only]($read_only_style)"
read_only = "  "
use_os_path_sep = true
style = "purple"
truncation_length = 3
truncation_symbol = "…/"

[localip]
ssh_only = true
format = " ◯[$localipv4](bold magenta)"
disabled = false

[git_branch]
format = " on [$symbol$branch]($style)"
style = "bold green"
symbol = " "

[git_status]
format = '[ $all_status$ahead_behind]($style)'
style = ""
conflicted = ''
untracked = ''
stashed = ''
modified = ''
staged = '[++\($count\)](fg:green)'
renamed = ''
deleted = ''

[deno]
format = " [deno](italic) [∫ $version](green bold)"
version_format = "${raw}"

[lua]
format = " [lua](italic) [${symbol}${version}]($style)"
version_format = "${raw}"
symbol = " "
style = "bold bright-yellow"

[nodejs]
format = " [node](italic) [ ($version)](bold bright-green)"
version_format = "${raw}"
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
detect_extensions = []

[python]
format = " [py](italic) [${symbol}${version}]($style)"
symbol = " "
version_format = "${raw}"
style = "bold bright-yellow"

[ruby]
format = " [rb](italic) [${symbol}${version}]($style)"
symbol = " "
version_format = "${raw}"
style = "bold red"

[rust]
format = " [rs](italic) [$symbol$version]($style)"
symbol = ""
version_format = "${raw}"
style = "bold red"

[package]
format = " [pkg](italic dimmed) [$symbol$version]($style)"
version_format = "${raw}"
symbol = " "
style = "dimmed yellow italic bold"

[swift]
format = " [sw](italic) [${symbol}${version}]($style)"
symbol = " "
style = "bold bright-red"
version_format = "${raw}"

[aws]
disabled = true
format = " [aws](italic) [$symbol $profile $region]($style)"
style = "bold blue"
symbol = " "

[c]
symbol = " "
format = " [$symbol($version(-$name))]($style)"

[conda]
symbol = " "
format = " conda [$symbol$environment]($style)"

[docker_context]
symbol = " "
format = " docker [$symbol$context]($style)"

[golang]
symbol = "󰟓 "
format = " go [$symbol($version )]($style)"

[java]
symbol = " "
format = " java [${symbol}(${version} )]($style)"
